name: poc
description: Proof of Concept - TMMT
# version: 1.0.0
# homepage: https://www.retired.kiwi
# author: Chris Reynolds <chrisr@retired.kiwi>

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0
  mustache_template: ^2.0.0
  csslib: ^0.17.1

dev_dependencies:
  lint: ^1.7.2
  test: ^1.18.2
