name: poc
description: Proof of Concept - TMMT
# version: 1.0.0
# homepage: https://www.example.com
# author: Chris Reynolds <chrisr@retired.kiwi>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.0
  yaml: ^2.2.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
